In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [34]:
import numpy as np

## 20. Create a 2D array containing random floats between 5 and 10
<pre>Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

Desired Output:
array([[5.07634273, 7.32940897, 5.78840303],
       [9.53547942, 7.16008125, 7.67112179],
       [7.42716913, 9.014935  , 9.20378359],
       [6.28776986, 5.7333183 , 6.7932973 ],
       [8.92046486, 7.80469775, 7.51347921]])</pre>

In [3]:
np.random.uniform(5, 10, size=(5,3))

array([[5.22198182, 8.35154157, 5.39805448],
       [7.60986434, 7.42392035, 7.67698422],
       [5.56196533, 9.46381912, 7.51806001],
       [6.34622408, 8.75681887, 9.87134082],
       [6.96799154, 6.43375714, 8.40962   ]])

# random.normal

## 21. Print only 3 decimal places in python numpy array
<pre>Print or show only 3 decimal places of the numpy array rand_arr.

Given Input:
rand_arr = np.random.random((2,2))</pre>

In [15]:
rand_arr = np.random.random((2,2)) #random. random is uniform 
rand_arr

array([[0.805, 0.679],
       [0.724, 0.152]])

In [10]:
rand_arr = np.set_printoptions(precision=3)
print(rand_arr)

None


## 22. Print a scientific notation (like 1e10) numpy array to standard notation
<pre>Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Given Input:
rand_arr = np.random.random([3,3])/1e3
rand_arr
$> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
          [  8.447761e-04,   4.718856e-06,   1.215691e-04],
          [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:
$> array([[ 0.000543,  0.000278,  0.000425],
          [ 0.000845,  0.000005,  0.000122],
          [ 0.000671,  0.000826,  0.000137]])</pre>

In [3]:
1e3

1000.0

In [6]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.00092635, 0.00012757, 0.00033721],
       [0.00028129, 0.00020006, 0.0004609 ],
       [0.00064856, 0.0008983 , 0.00087614]])

In [10]:
np.set_printoptions(suppress = True, precision =6)
rand_arr

array([[0.000926, 0.000128, 0.000337],
       [0.000281, 0.0002  , 0.000461],
       [0.000649, 0.000898, 0.000876]])

In [11]:
np.set_printoptions(suppress = False)
rand_arr

array([[0.000926, 0.000128, 0.000337],
       [0.000281, 0.0002  , 0.000461],
       [0.000649, 0.000898, 0.000876]])

## 23. Limit the number of items printed in output of numpy array
<pre>Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Given Input:
a = np.arange(15)
$> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:
$> array([ 0,  1,  2, ..., 12, 13, 14])
</pre>

In [30]:

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.set_printoptions(suppress = True, threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

In [41]:
np.set_printoptions(threshold=6)

a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [42]:
np.set_printoptions(threshold=np.inf) # undo 

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 24. Print the full numpy array without truncating
<pre>Print the full numpy array a without truncating.

Given Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
a
$> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:
a
$> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])</pre>

In [54]:
np.set_printoptions(threshold = 6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [56]:
np.set_printoptions(threshold = np.inf)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. Import a dataset with numbers and texts keeping the text intact in python numpy
<pre>Import the iris dataset keeping the text intact.
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       ...
</pre>

In [18]:

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

iris = np.genfromtxt(
    url,
    delimiter=",",
    dtype=None,
    encoding=None
)

iris

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'), ...,
       (6.5, 3. , 5.2, 2. , 'Iris-virginica'),
       (6.2, 3.4, 5.4, 2.3, 'Iris-virginica'),
       (5.9, 3. , 5.1, 1.8, 'Iris-virginica')],
      shape=(150,), dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', '<U15')])

In [22]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


iris = np.genfromtxt(
    url,
    delimiter=',',
    dtype={
        'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
        'formats': ('f4', 'f4', 'f4', 'f4', 'object')
    }
)

iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'), ...,
       (6.5, 3. , 5.2, 2. , b'Iris-virginica'),
       (6.2, 3.4, 5.4, 2.3, b'Iris-virginica'),
       (5.9, 3. , 5.1, 1.8, b'Iris-virginica')],
      shape=(150,), dtype=[('sepallength', '<f4'), ('sepalwidth', '<f4'), ('petallength', '<f4'), ('petalwidth', '<f4'), ('species', 'O')])

## 26. Compute the mean, median, standard deviation of a numpy array
<pre>Find the mean, median, standard deviation of iris's sepallength (1st column)
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
[5.843333333333334, 5.8, 0.8253012917851409]
</pre>

In [19]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [29]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print([mu, med, sd])

[np.float64(5.843333333333334), np.float64(5.8), np.float64(0.8253012917851409)]


## 27. Find the percentile scores of a numpy array
<pre>Find the 5th and 95th percentile of iris's sepallength

Given Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0]) 

Desired Output:
array([4.6  , 7.255])</pre>


In [35]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

percentiles = np.percentile(sepallength, [5, 95])
percentiles

array([4.6  , 7.255])

## 28. Find the position of missing value in numpy array
<pre>
Find: 
1. Number of missing values
2. Row number that contains missing values
3. The NaN row value

Given Input:
arr = np.array([[1, 2, 3],
                [4, np.NaN, 6],
                [7, 8, 9],
                [np.NaN, np.NaN, np.NaN]
               ])

Desired Output:
Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]</pre>

In [37]:
arr = np.array([[1,2,3],
                [4,np.nan,6],
                [7,8,9],
                [np.nan,np.nan,np.nan]
               ])
arr

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [nan, nan, nan]], shape=(4, 3))

In [6]:
print("Number of missing values: \n",)
print("Row contains missing values: \n",  )
print("The NaN row: \n",)

Number of missing values: 

Row contains missing values: 

The NaN row: 



In [38]:
# 1. Number of missing values
num_missing = np.isnan(arr).sum()
print("Number of missing values:\n", num_missing)

# 2. Row number that contains missing values
rows_with_nan = np.where(np.isnan(arr).any(axis=1))
print("Row contains missing values:\n", rows_with_nan)

# 3. The NaN row value
nan_rows = arr[rows_with_nan]
print("The NaN row:\n", nan_rows)

Number of missing values:
 4
Row contains missing values:
 (array([1, 3]),)
The NaN row:
 [[ 4. nan  6.]
 [nan nan nan]]


## 29. Filter with conditions
<pre>
Filter the first column < 9 and fourth column > 4
Given Input:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])

Desired Output:
$> arr[conditions]
array([[5, 6, 7, 8]])

In [40]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], shape=(3, 4))

In [43]:
conditions = (arr[:, 0] < 9) & (arr[:, 3] > 4)

In [44]:
arr[conditions]

array([[5, 6, 7, 8]])

## 30. Inverse set of array
<pre>Multiply the non-NaN array by 2
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]
$> array([[ 4., nan,  6.],
         [nan, nan, nan]])
         
Desired Output:
array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

In [7]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]

array([[ 4., nan,  6.],
       [nan, nan, nan]])

### ~ means the inverse set of given array

In [51]:

 arr[~np.any(np.isnan(arr), axis=1)] * 2


array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

## 31. Drop rows that contain a missing value from a numpy array
<pre>
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
               
Desired Output:
array([[1., 2., 3.],
       [7., 8., 9.]])
</pre>

In [53]:
arr = np.array([[1,2,3],
                [4,np.nan,6],
                [7,8,9],
                [np.nan,np.nan,np.nan]
               ])

In [55]:
 arr[~np.any(np.isnan(arr), axis=1)]

array([[1., 2., 3.],
       [7., 8., 9.]])

## 32. Find the correlation coefficient between two numpy array
<pre>
Find the correlation of array a and b
Given Input:
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

Desired Output:
$> array([[1.        , 0.99747669],
       [0.99747669, 1.        ]])</pre>


In [4]:
import numpy as np
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

In [5]:
# Find the correlation between a and b


array([[1.        , 0.99747669],
       [0.99747669, 1.        ]])

## 33. Count NaN and non-NaN in numpy array
<pre> 
Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> There are 5 non-NaN.
$> There are 3 NaN.</pre> 


In [30]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [31]:
print(f"There are ??? non-NaN.")

There are 5 non-NaN.


In [8]:
print(f"There are ??? NaN.")

There are ??? NaN.


## 34. Replace all missing values with 0 in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> array([0., 1., 2., 3., 0., 5., 0., 0.])
</pre> 

In [33]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

## 35. Replace all missing values with mean in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])

Desired Output:
$> arr
array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])</pre>

In [35]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])

## 36. Find the count of unique values in a numpy array
<pre>Given Input:
$> stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
$> stud_gender
['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

Desired Output:</pre>
(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

In [12]:
stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
stud_gender

['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

In [13]:
np.unique(stud_gender)

array(['Female', 'Male'], dtype='<U6')

(array(['Female', 'Male'], dtype='<U6'), array([4, 3], dtype=int64))

## 37. Convert numeric value to categoric value
<pre>Given Input:
$> stud_result = np.random.randint(0, 100, size=50)
$> stud_result
array([ 9, 86,  6, 67, 14, 64, 18, 83,  5, 66, 15, 68, 66, 58,  1, 64,  8,
       64, 97, 12, 45, 12,  1,  0, 21, 75, 12, 15, 46, 76, 50, 21,  2, 31,
        5, 54, 91, 48, 10, 89, 52, 61, 52, 85, 40, 28,  3, 29, 20, 40])

Desired Output:
Categorize the reult in 'Fail':below 50, 'Pass':blow 70, 'Good':below 100'
['Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Good',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Pass',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Pass',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Pass']
</pre>

In [40]:
stud_result = np.random.randint(0, 100, size=50)
stud_result

array([35, 96, 46, 65,  8, 59, 12, 47, 21, 17, 83, 94, 50,  4, 66, 25, 58,
       87, 68, 69, 19, 86, 59, 64, 67, 45, 76,  6, 58, 39, 60,  9, 98, 17,
       15, 62, 54, 42, 28, 50, 30, 22, 98, 27, 76, 42, 46, 93, 35, 59])

In [41]:
# digitize the result in to 4 ranges 


array([1, 3, 1, 2, 1, 2, 1, 1, 1, 1, 3, 3, 2, 1, 2, 1, 2, 3, 2, 2, 1, 3,
       2, 2, 2, 1, 3, 1, 2, 1, 2, 1, 3, 1, 1, 2, 2, 1, 1, 2, 1, 1, 3, 1,
       3, 1, 1, 3, 1, 2], dtype=int64)

In [42]:
cat_label = {1:'Fail', 2:'Pass', 3:'Good'}

['Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Good',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Pass',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Pass',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Pass']