In [115]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [116]:
import numpy as np

## 20. Create a 2D array containing random floats between 5 and 10
<pre>Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

Desired Output:
array([[5.07634273, 7.32940897, 5.78840303],
       [9.53547942, 7.16008125, 7.67112179],
       [7.42716913, 9.014935  , 9.20378359],
       [6.28776986, 5.7333183 , 6.7932973 ],
       [8.92046486, 7.80469775, 7.51347921]])</pre>

In [117]:
np.random.uniform(5, 10, size=(5,3))

array([[7.929609, 9.019456, 5.199327],
       [8.98586 , 7.569563, 9.475763],
       [7.349366, 5.496121, 8.464075],
       [7.595507, 6.238293, 5.960364],
       [6.219739, 9.134097, 7.77223 ]])

# random.normal

## 21. Print only 3 decimal places in python numpy array
<pre>Print or show only 3 decimal places of the numpy array rand_arr.

Given Input:
rand_arr = np.random.random((2,2))</pre>

In [118]:
rand_arr = np.random.random((2,2)) #random. random is uniform 
rand_arr

array([[0.181805, 0.108548],
       [0.7961  , 0.210222]])

In [119]:
rand_arr = np.set_printoptions(precision=3)


## 22. Print a scientific notation (like 1e10) numpy array to standard notation
<pre>Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Given Input:
rand_arr = np.random.random([3,3])/1e3
rand_arr
$> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
          [  8.447761e-04,   4.718856e-06,   1.215691e-04],
          [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:
$> array([[ 0.000543,  0.000278,  0.000425],
          [ 0.000845,  0.000005,  0.000122],
          [ 0.000671,  0.000826,  0.000137]])</pre>

In [120]:
1e3

1000.0

In [ ]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

In [122]:
np.set_printoptions(suppress = True, precision =6)
rand_arr

array([[0.000454, 0.000273, 0.000184],
       [0.000132, 0.000276, 0.000576],
       [0.001   , 0.000175, 0.00009 ]])

In [123]:
np.set_printoptions(suppress = False)
rand_arr

array([[4.538276e-04, 2.731552e-04, 1.841651e-04],
       [1.315691e-04, 2.758299e-04, 5.755279e-04],
       [9.998876e-04, 1.750382e-04, 9.032427e-05]])

## 23. Limit the number of items printed in output of numpy array
<pre>Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Given Input:
a = np.arange(15)
$> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:
$> array([ 0,  1,  2, ..., 12, 13, 14])
</pre>

In [124]:

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
np.set_printoptions(suppress = True, threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

In [142]:
np.set_printoptions(threshold=6)

a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [143]:
np.set_printoptions(threshold=np.inf) # undo 

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 24. Print the full numpy array without truncating
<pre>Print the full numpy array a without truncating.

Given Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
a
$> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:
a
$> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])</pre>

In [128]:
np.set_printoptions(threshold = 6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

In [129]:
np.set_printoptions(threshold = np.inf)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. Import a dataset with numbers and texts keeping the text intact in python numpy
<pre>Import the iris dataset keeping the text intact.
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       ...
</pre>

In [130]:

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

iris = np.genfromtxt(
    url,
    delimiter=",",
    dtype=None,
    encoding=None
)

iris

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iri

In [131]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


iris = np.genfromtxt(
    url,
    delimiter=',',
    dtype={
        'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
        'formats': ('f4', 'f4', 'f4', 'f4', 'object')
    }
)

iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

## 26. Compute the mean, median, standard deviation of a numpy array
<pre>Find the mean, median, standard deviation of iris's sepallength (1st column)
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
[5.843333333333334, 5.8, 0.8253012917851409]
</pre>

In [132]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [133]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print([mu, med, sd])

[np.float64(5.843333333333334), np.float64(5.8), np.float64(0.8253012917851409)]


## 27. Find the percentile scores of a numpy array
<pre>Find the 5th and 95th percentile of iris's sepallength

Given Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0]) 

Desired Output:
array([4.6  , 7.255])</pre>


In [134]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

percentiles = np.percentile(sepallength, [5, 95])
percentiles

array([4.6  , 7.255])

## 28. Find the position of missing value in numpy array
<pre>
Find: 
1. Number of missing values
2. Row number that contains missing values
3. The NaN row value

Given Input:
arr = np.array([[1, 2, 3],
                [4, np.NaN, 6],
                [7, 8, 9],
                [np.NaN, np.NaN, np.NaN]
               ])

Desired Output:
Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]</pre>

In [146]:
arr = np.array([[1,2,3],
                [4,np.nan,6],
                [7,8,9],
                [np.nan,np.nan,np.nan]
               ])
arr

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [nan, nan, nan]])

In [147]:
num_missing = np.isnan(arr).sum
print("Number of missing values: \n", num_missing)

row_with_nan = np.where(np.isnan(arr).any(axis=1))
print("Row contains missing values: \n", row_with_nan)

nan_row = arr[row_with_nan]
print("The NaN row: \n", nan_row)

Number of missing values: 
 <built-in method sum of numpy.ndarray object at 0x106546070>
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]


In [137]:
# 1. Number of missing values
num_missing = np.isnan(arr).sum()
print("Number of missing values:\n", num_missing)

# 2. Row number that contains missing values
rows_with_nan = np.where(np.isnan(arr).any(axis=1))
print("Row contains missing values:\n", rows_with_nan)

# 3. The NaN row value
nan_rows = arr[rows_with_nan]
print("The NaN row:\n", nan_rows)

Number of missing values:
 4
Row contains missing values:
 (array([1, 3]),)
The NaN row:
 [[ 4. nan  6.]
 [nan nan nan]]


## 29. Filter with conditions
<pre>
Filter the first column < 9 and fourth column > 4
Given Input:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])

Desired Output:
$> arr[conditions]
array([[5, 6, 7, 8]])

In [156]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [165]:
conditions = (arr[:,0] <9) & (arr[:,3] >4)


In [166]:
arr[conditions]

array([[5, 6, 7, 8]])

## 30. Inverse set of array
<pre>Multiply the non-NaN array by 2
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]
$> array([[ 4., nan,  6.],
         [nan, nan, nan]])
         
Desired Output:
array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

In [167]:
arr = np.array([[1,2,3],
                [4,np.nan,6],
                [7,8,9],
                [np.nan,np.nan,np.nan]
               ])
arr[np.any(np.isnan(arr), axis=1)]

array([[ 4., nan,  6.],
       [nan, nan, nan]])

### ~ means the inverse set of given array

In [168]:

 arr[~np.any(np.isnan(arr), axis=1)] * 2


array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

## 31. Drop rows that contain a missing value from a numpy array
<pre>
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
               
Desired Output:
array([[1., 2., 3.],
       [7., 8., 9.]])
</pre>

In [ ]:
arr = np.array([[1,2,3],
                [4,np.nan,6],
                [7,8,9],
                [np.nan,np.nan,np.nan]
               ])

In [ ]:
 arr[~np.any(np.isnan(arr), axis=1)]

# .corrcoef

## 32. Find the correlation coefficient between two numpy array
<pre>
Find the correlation of array a and b
Given Input:
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

Desired Output:
$> array([[1.        , 0.99747669],
       [0.99747669, 1.        ]])</pre>


In [170]:
import numpy as np
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

In [171]:
# Find the correlation between a and b
corr = np.corrcoef(a, b)
corr

array([[1.      , 0.997477],
       [0.997477, 1.      ]])

# isnan 

## 33. Count NaN and non-NaN in numpy array
<pre> 
Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> There are 5 non-NaN.
$> There are 3 NaN.</pre> 


In [172]:
arr = np.array([0, 1, 2, 3, np.nan, 5, np.nan, np.nan])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [173]:
num_nan = np.isnan(arr).sum()
print(f"There are {num_nan} non-NaN.")

There are 3 non-NaN.


In [174]:
non_nan = (~np.isnan(arr)).sum()
print(f"There are {non_nan} NaN.")

There are 5 NaN.


## 34. Replace all missing values with 0 in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> array([0., 1., 2., 3., 0., 5., 0., 0.])
</pre> 

In [175]:
arr = np.array([0, 1, 2, 3, np.nan, 5, np.nan, np.nan])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [178]:
arr[np.isnan(arr)] = 0
arr

array([0., 1., 2., 3., 0., 5., 0., 0.])

## 35. Replace all missing values with mean in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])

Desired Output:
$> arr
array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])</pre>

In [182]:
arr = np.array([0, 1, 2, 3, np.nan, 5, np.nan, np.nan])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [183]:
arr[np.isnan(arr)] = np.mean(arr[~np.isnan(arr)])
arr

array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])

# unique

## 36. Find the count of unique values in a numpy array
<pre>Given Input:
$> stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
$> stud_gender
['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

Desired Output:</pre>
(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

In [ ]:
stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
stud_gender

In [ ]:
np.unique(stud_gender)

In [184]:
np.unique(stud_gender, return_counts = True) # return_counts is arguments


(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

In [185]:
gender, counts = np.unique(stud_gender, return_counts= True)
print (gender[0], counts[0])

Female 4


# Zip, digitize

## 37. Convert numeric value to categoric value
<pre>Given Input:
$> stud_result = np.random.randint(0, 100, size=50)
$> stud_result
array([ 9, 86,  6, 67, 14, 64, 18, 83,  5, 66, 15, 68, 66, 58,  1, 64,  8,
       64, 97, 12, 45, 12,  1,  0, 21, 75, 12, 15, 46, 76, 50, 21,  2, 31,
        5, 54, 91, 48, 10, 89, 52, 61, 52, 85, 40, 28,  3, 29, 20, 40])

Desired Output:
Categorize the reult in 'Fail':below 50, 'Pass':blow 70, 'Good':below 100'
['Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Good',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Pass',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Pass',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Pass']
</pre>

In [186]:
stud_result = np.random.randint(0, 101, size=50) # random 0 -100, output 50 int
stud_result

array([ 28,  87, 100,   8,  67,  84,   4,   7,  71,  96,  79,  40,  16,
        47,   5,  81,  49,  22,  97,  34,   3,  89,  58,   9,  46,  59,
        33,  70,   8,  89,  73,  54,  70,  30,   4,   5,  18,  11,  93,
        80,  53,  43,  78,  85,  71,  81,  78,  90,  94,  94])

In [189]:
# digitize the result in to 4 ranges 
cat = np.digitize(stud_result, np.array([0, 50, 70 , 101]), right = False)
cat

array([1, 3, 3, 1, 2, 3, 1, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3,
       2, 1, 1, 2, 1, 3, 1, 3, 3, 2, 3, 1, 1, 1, 1, 1, 3, 3, 2, 1, 3, 3,
       3, 3, 3, 3, 3, 3])

In [ ]:
cat_label = {1:'Fail', 2:'Pass', 3:'Good'} # dictionay 

In [190]:
result_in_cat = [cat_label[x] for x in cat]
result_in_cat

['Fail',
 'Good',
 'Good',
 'Fail',
 'Pass',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Fail',
 'Good',
 'Good',
 'Good',
 'Good',
 'Good',
 'Good',
 'Good',
 'Good']

In [192]:
dict(zip(stud_result, result_in_cat)) # array 一定要用zip 做 dictionary


{np.int64(28): 'Fail',
 np.int64(87): 'Good',
 np.int64(100): 'Good',
 np.int64(8): 'Fail',
 np.int64(67): 'Pass',
 np.int64(84): 'Good',
 np.int64(4): 'Fail',
 np.int64(7): 'Fail',
 np.int64(71): 'Good',
 np.int64(96): 'Good',
 np.int64(79): 'Good',
 np.int64(40): 'Fail',
 np.int64(16): 'Fail',
 np.int64(47): 'Fail',
 np.int64(5): 'Fail',
 np.int64(81): 'Good',
 np.int64(49): 'Fail',
 np.int64(22): 'Fail',
 np.int64(97): 'Good',
 np.int64(34): 'Fail',
 np.int64(3): 'Fail',
 np.int64(89): 'Good',
 np.int64(58): 'Pass',
 np.int64(9): 'Fail',
 np.int64(46): 'Fail',
 np.int64(59): 'Pass',
 np.int64(33): 'Fail',
 np.int64(70): 'Good',
 np.int64(73): 'Good',
 np.int64(54): 'Pass',
 np.int64(30): 'Fail',
 np.int64(18): 'Fail',
 np.int64(11): 'Fail',
 np.int64(93): 'Good',
 np.int64(80): 'Good',
 np.int64(53): 'Pass',
 np.int64(43): 'Fail',
 np.int64(78): 'Good',
 np.int64(85): 'Good',
 np.int64(90): 'Good',
 np.int64(94): 'Good'}

In [200]:
[(str(x) + '-Good'
     if x > 70
         else
             str(x) + '-Pass')
                 if x > 50
                     else
                       str(x)+'-Fall'
 for x in stud_result
]

['28-Fall',
 '87-Good',
 '100-Good',
 '8-Fall',
 '67-Pass',
 '84-Good',
 '4-Fall',
 '7-Fall',
 '71-Good',
 '96-Good',
 '79-Good',
 '40-Fall',
 '16-Fall',
 '47-Fall',
 '5-Fall',
 '81-Good',
 '49-Fall',
 '22-Fall',
 '97-Good',
 '34-Fall',
 '3-Fall',
 '89-Good',
 '58-Pass',
 '9-Fall',
 '46-Fall',
 '59-Pass',
 '33-Fall',
 '70-Pass',
 '8-Fall',
 '89-Good',
 '73-Good',
 '54-Pass',
 '70-Pass',
 '30-Fall',
 '4-Fall',
 '5-Fall',
 '18-Fall',
 '11-Fall',
 '93-Good',
 '80-Good',
 '53-Pass',
 '43-Fall',
 '78-Good',
 '85-Good',
 '71-Good',
 '81-Good',
 '78-Good',
 '90-Good',
 '94-Good',
 '94-Good']

# .digitize

In [198]:
x = np.array([1.2,10.0,12.4, 15.5, 20])
bins = np.array([0,4,10,15,20])
np.digitize(x, bins, right = True)

array([1, 2, 3, 4, 4])

In [199]:
np.digitize(x, bins, right = False)

array([1, 3, 3, 4, 5])