# Scalar and Vector 

Scalr - 標量
vector - 向量
Matrix - 距陣
metric - 效能

In [1]:
import numpy as np
# scalar
s = 1

In [3]:
# vector
v1 = np.array([1,4,5])
v2 = np.array([[1],[-5]])
print ('v1 shape: ', v1.shape)
print ('v2 shape: ', v2.shape)

v1 shape:  (3,)
v2 shape:  (2, 1)


In [5]:
m = np.array ([[1,4,5],[-5,8,9]])
m

array([[ 1,  4,  5],
       [-5,  8,  9]])

In [9]:
m1 = np.array ([[1,4,5],[-5,'a',True]])
m1

array([['1', '4', '5'],
       ['-5', 'a', 'True']], dtype='<U21')

In [8]:
m.shape

(2, 3)

# arange -> 自動出數

In [11]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [30]:

a = np.reshape(a, (3, 2))
print(a)


[[0 1]
 [2 3]
 [4 5]]


# .T - 將colnum 變ROW

In [15]:
b = np.array([[1,2],
             [3,4],
              [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
b.T

array([[1, 3, 5],
       [2, 4, 6]])

# .fatten

In [18]:
b = np.array([[1,2],
             [3,4],
             [5,6]])
b.flatten()

array([1, 2, 3, 4, 5, 6])

# .concatenate((a,b), axis = 0)


In [19]:
a = np.array([[1,2],[3,4]])
b = np.array ([[5,6]])
np.concatenate ((a,b), axis = 0) #o  = concat by row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
b

array([[5, 6]])

In [25]:
b.T

array([[5],
       [6]])

In [ ]:
 # 1 係打直，打直係colnums

In [20]:
np.concatenate ((a,b.T), axis = 1) 

array([[1, 2, 5],
       [3, 4, 6]])

# .split <- 平均分(x,3)= 分3份

In [31]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr1, arr2, arr3 = np.split(x,3)
arr1

array([0, 1, 2])

In [36]:
x.shape 

(9,)

In [35]:
 np.split(x,[4,6]) # <- colnum 第4行拆 & 第6行拆

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [38]:
 np.split(x,[4,6])[1] #<-- split 咗後嘅 index 1 , 即第二個array

array([4, 5])

In [40]:
 np.split(x,[4,6])[2]  #<-- split 咗後嘅 index 2, 即第3個array

array([6, 7, 8])

# v.split

In [43]:
x = np.arange(16). reshape(4,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [47]:
np.vsplit(x,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# .hsplit

In [48]:
x = np.arange(16). reshape(4,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
np.hsplit(x,[1])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

# .delete

In [51]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.delete(arr, 2, axis=0) #<=v(arr, 第幾行，axis = 0 /1 row/ colnum)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
np.delete(arr, np.s_[2], axis=1) #<-- handle 多D data 會run 快D

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [59]:
np.delete(arr, 2, axis=1) #<- 同 np.s_[2] 一樣

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

# .unique #<- 搵array label

In [60]:
b = np.array([1,2,1,2,5,3,3])
np.unique(b)

array([1, 2, 3, 5])

In [66]:
r = np.array([[1,0,0],[1,0,0],[2,4,4]])
r

array([[1, 0, 0],
       [1, 0, 0],
       [2, 4, 4]])

In [67]:
r = np.array([[1,0,0],[1,0,0],[2,4,4]])
np.unique(r, axis = 0) #<- return unique row

array([[1, 0, 0],
       [2, 4, 4]])

In [64]:
a = np.array ([1,2,6,4,2,3,2])
values, counts = np.unique(a, return_counts = True)
values # arr of unique val

array([1, 2, 3, 4, 6])

# .truncate decimal

In [69]:
arr = np.array([-1.99, -1.13, 0.56, 1.28, 2.10, 2.65])
arr

array([-1.99, -1.13,  0.56,  1.28,  2.1 ,  2.65])

In [70]:
np.trunc(arr)

array([-1., -1.,  0.,  1.,  2.,  2.])

In [71]:
# round to nearest interger towards zero
np.fix(arr)

array([-1., -1.,  0.,  1.,  2.,  2.])

In [ ]:
# round off to n decimal point, python use even round in case of error after many
