In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [5]:
python_list = [1, 'a', True, 9.9]
print (python_list)
type(python_list)

[1, 'a', True, 9.9]


list

# Create 1-D numpy array <-- np.array 轉所有datatype 做str

In [12]:
np.array([1, 'a', True, 9.9]) #多種data type -> pops 靈活，   #單一data -> faster handel 

array(['1', 'a', 'True', '9.9'], dtype='<U32')

In [16]:
arr = np.array([1,2,3,4])
print(arr)
type(arr)

[1 2 3 4]


numpy.ndarray

In [17]:
arr.shape

(4,)

In [18]:
arr.ndim

1

In [19]:
arr.size

4

# Slicing 1-D array

In [21]:
arr2 = np.array([1,2,3])
print(arr2[0]) #1
print(arr2[1]) #2
print(arr2[-1])#3
print(arr2[:]) #[1 2 3]
print(arr2[1:]) #[ 2 3]
print(arr2[:2]) #[1 2]

1
2
3
[1 2 3]
[2 3]
[1 2]


In [22]:
arr_2D = np.array([[1,2],[3,4],[5,6],[7,8]])
print (arr_2D)
arr_2D.shape  #(4,2) =  4 row, 2 colnum 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)

In [23]:
arr_2D.size

8

# slicing 2D array

In [25]:
arr_2D = np.array([[1,2,],[3,4],[5,6],[7,8]])
print(arr_2D[1])
print(arr_2D[3][0])
print(arr_2D[:2])

[3 4]
7
[[1 2]
 [3 4]]
